# Generated by Django 3.1.4 on 2020-12-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Rating', models.IntegerField(default=0)),
                ('Pages', models.IntegerField(default=0)),
                ('Checked', models.BooleanField()),
            ],
        ),
    ]
